repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: [--line-length=79]
        types: [python]
        language_version: python3.6
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.0.0
    hooks:
      - id: seed-isort-config
        language_version: python3.6
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
      - id: isort
        types: [python]
        language_version: python3.6
