language: python
python: 2.7
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py27-green
    - TOX_ENV=py33
    - TOX_ENV=py33-green
    - TOX_ENV=py34
    - TOX_ENV=py34-green
    - TOX_ENV=docs
    - TOX_ENV=flake8

install:
    - pip install tox coveralls

script:
    - tox -e $TOX_ENV

after_success:
    - coveralls
